// Code generated by badctl v0.0.0, DO NOT EDIT.
package integrationtests

import badorm "github.com/ditrit/badaas/badorm"

func SellerNameCondition(v string) badorm.WhereCondition[Seller] {
	return badorm.WhereCondition[Seller]{
		Field: "name",
		Value: v,
	}
}
