// Code generated by badctl v0.0.0, DO NOT EDIT.
package integrationtests

import badorm "github.com/ditrit/badaas/badorm"

func BicycleNameCondition(v string) badorm.WhereCondition[Bicycle] {
	return badorm.WhereCondition[Bicycle]{
		Field: "name",
		Value: v,
	}
}
