// Code generated by badctl v0.0.0, DO NOT EDIT.
package integrationtests

import badorm "github.com/ditrit/badaas/badorm"

func EmployeeNameCondition(v string) badorm.WhereCondition[Employee] {
	return badorm.WhereCondition[Employee]{
		Field: "name",
		Value: v,
	}
}
