// Code generated by badctl v0.0.0, DO NOT EDIT.
package integrationtests

import badorm "github.com/ditrit/badaas/badorm"

func SaleCodeCondition(v int) badorm.WhereCondition[Sale] {
	return badorm.WhereCondition[Sale]{
		Field: "code",
		Value: v,
	}
}
func SaleDescriptionCondition(v string) badorm.WhereCondition[Sale] {
	return badorm.WhereCondition[Sale]{
		Field: "description",
		Value: v,
	}
}
