// Code generated by badctl v0.0.0, DO NOT EDIT.
package integrationtests

import badorm "github.com/ditrit/badaas/badorm"

func CityNameCondition(v string) badorm.WhereCondition[City] {
	return badorm.WhereCondition[City]{
		Field: "name",
		Value: v,
	}
}
