// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func BicycleId(operator orm.Operator[orm.UUID]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, orm.UUID]{
		Operator:      operator,
		FieldIdentifier: orm.IDFieldID,
	}
}
func BicycleCreatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, time.Time]{
		Operator:      operator,
		FieldIdentifier: orm.CreatedAtFieldID,
	}
}
func BicycleUpdatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, time.Time]{
		Operator:      operator,
		FieldIdentifier: orm.UpdatedAtFieldID,
	}
}
func BicycleDeletedAt(operator orm.Operator[gorm.DeletedAt]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, gorm.DeletedAt]{
		Operator:      operator,
		FieldIdentifier: orm.DeletedAtFieldID,
	}
}

var bicycleNameFieldID = orm.FieldIdentifier{Field: "Name"}

func BicycleName(operator orm.Operator[string]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, string]{
		Operator:      operator,
		FieldIdentifier: bicycleNameFieldID,
	}
}
func BicycleOwner(conditions ...orm.Condition[models.Person]) orm.IJoinCondition[models.Bicycle] {
	return orm.JoinCondition[models.Bicycle, models.Person]{
		Conditions:         conditions,
		RelationField:      "Owner",
		T1Field:            "OwnerName",
		T1PreloadCondition: BicyclePreloadAttributes,
		T2Field:            "Name",
	}
}

var BicyclePreloadOwner = BicycleOwner(PersonPreloadAttributes)
var bicycleOwnerNameFieldID = orm.FieldIdentifier{Field: "OwnerName"}

func BicycleOwnerName(operator orm.Operator[string]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, string]{
		Operator:      operator,
		FieldIdentifier: bicycleOwnerNameFieldID,
	}
}

var BicyclePreloadAttributes = orm.NewPreloadCondition[models.Bicycle](bicycleNameFieldID, bicycleOwnerNameFieldID)
var BicyclePreloadRelations = []orm.Condition[models.Bicycle]{BicyclePreloadOwner}
