// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"reflect"
	"time"
)

var bicycleType = reflect.TypeOf(*new(models.Bicycle))
var BicycleIdField = badorm.FieldIdentifier[badorm.UUID]{
	Field:     "ID",
	ModelType: bicycleType,
}

func BicycleId(operator badorm.Operator[badorm.UUID]) badorm.WhereCondition[models.Bicycle] {
	return badorm.FieldCondition[models.Bicycle, badorm.UUID]{
		FieldIdentifier: BicycleIdField,
		Operator:        operator,
	}
}

var BicycleCreatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "CreatedAt",
	ModelType: bicycleType,
}

func BicycleCreatedAt(operator badorm.Operator[time.Time]) badorm.WhereCondition[models.Bicycle] {
	return badorm.FieldCondition[models.Bicycle, time.Time]{
		FieldIdentifier: BicycleCreatedAtField,
		Operator:        operator,
	}
}

var BicycleUpdatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "UpdatedAt",
	ModelType: bicycleType,
}

func BicycleUpdatedAt(operator badorm.Operator[time.Time]) badorm.WhereCondition[models.Bicycle] {
	return badorm.FieldCondition[models.Bicycle, time.Time]{
		FieldIdentifier: BicycleUpdatedAtField,
		Operator:        operator,
	}
}

var BicycleDeletedAtField = badorm.FieldIdentifier[gorm.DeletedAt]{
	Field:     "DeletedAt",
	ModelType: bicycleType,
}

func BicycleDeletedAt(operator badorm.Operator[gorm.DeletedAt]) badorm.WhereCondition[models.Bicycle] {
	return badorm.FieldCondition[models.Bicycle, gorm.DeletedAt]{
		FieldIdentifier: BicycleDeletedAtField,
		Operator:        operator,
	}
}

var BicycleNameField = badorm.FieldIdentifier[string]{
	Field:     "Name",
	ModelType: bicycleType,
}

func BicycleName(operator badorm.Operator[string]) badorm.WhereCondition[models.Bicycle] {
	return badorm.FieldCondition[models.Bicycle, string]{
		FieldIdentifier: BicycleNameField,
		Operator:        operator,
	}
}
func BicycleOwner(conditions ...badorm.Condition[models.Person]) badorm.IJoinCondition[models.Bicycle] {
	return badorm.JoinCondition[models.Bicycle, models.Person]{
		Conditions:         conditions,
		RelationField:      "Owner",
		T1Field:            "OwnerName",
		T1PreloadCondition: BicyclePreloadAttributes,
		T2Field:            "Name",
	}
}

var BicyclePreloadOwner = BicycleOwner(PersonPreloadAttributes)
var BicycleOwnerNameField = badorm.FieldIdentifier[string]{
	Field:     "OwnerName",
	ModelType: bicycleType,
}

func BicycleOwnerName(operator badorm.Operator[string]) badorm.WhereCondition[models.Bicycle] {
	return badorm.FieldCondition[models.Bicycle, string]{
		FieldIdentifier: BicycleOwnerNameField,
		Operator:        operator,
	}
}

var BicyclePreloadAttributes = badorm.NewPreloadCondition[models.Bicycle](BicycleIdField, BicycleCreatedAtField, BicycleUpdatedAtField, BicycleDeletedAtField, BicycleNameField, BicycleOwnerNameField)
var BicyclePreloadRelations = []badorm.Condition[models.Bicycle]{BicyclePreloadOwner}
