// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func BrandId(expr badorm.Expression[uint]) badorm.WhereCondition[models.Brand] {
	return badorm.FieldCondition[models.Brand, uint]{
		Expression:      expr,
		FieldIdentifier: badorm.IDFieldID,
	}
}
func BrandCreatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.Brand] {
	return badorm.FieldCondition[models.Brand, time.Time]{
		Expression:      expr,
		FieldIdentifier: badorm.CreatedAtFieldID,
	}
}
func BrandUpdatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.Brand] {
	return badorm.FieldCondition[models.Brand, time.Time]{
		Expression:      expr,
		FieldIdentifier: badorm.UpdatedAtFieldID,
	}
}
func BrandDeletedAt(expr badorm.Expression[gorm.DeletedAt]) badorm.WhereCondition[models.Brand] {
	return badorm.FieldCondition[models.Brand, gorm.DeletedAt]{
		Expression:      expr,
		FieldIdentifier: badorm.DeletedAtFieldID,
	}
}

var brandNameFieldID = badorm.FieldIdentifier{Field: "Name"}

func BrandName(expr badorm.Expression[string]) badorm.WhereCondition[models.Brand] {
	return badorm.FieldCondition[models.Brand, string]{
		Expression:      expr,
		FieldIdentifier: brandNameFieldID,
	}
}

var BrandPreloadAttributes = badorm.NewPreloadCondition[models.Brand](brandNameFieldID)
var BrandPreloadRelations = []badorm.Condition[models.Brand]{}
