// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func BrandId(expr orm.Expression[uint]) orm.WhereCondition[models.Brand] {
	return orm.FieldCondition[models.Brand, uint]{
		Expression: expr,
		Field:      "ID",
	}
}
func BrandCreatedAt(expr orm.Expression[time.Time]) orm.WhereCondition[models.Brand] {
	return orm.FieldCondition[models.Brand, time.Time]{
		Expression: expr,
		Field:      "CreatedAt",
	}
}
func BrandUpdatedAt(expr orm.Expression[time.Time]) orm.WhereCondition[models.Brand] {
	return orm.FieldCondition[models.Brand, time.Time]{
		Expression: expr,
		Field:      "UpdatedAt",
	}
}
func BrandDeletedAt(expr orm.Expression[gorm.DeletedAt]) orm.WhereCondition[models.Brand] {
	return orm.FieldCondition[models.Brand, gorm.DeletedAt]{
		Expression: expr,
		Field:      "DeletedAt",
	}
}
func BrandName(expr orm.Expression[string]) orm.WhereCondition[models.Brand] {
	return orm.FieldCondition[models.Brand, string]{
		Expression: expr,
		Field:      "Name",
	}
}
