// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"reflect"
	"time"
)

var brandType = reflect.TypeOf(*new(models.Brand))
var BrandIdField = badorm.FieldIdentifier[badorm.UIntID]{
	Field:     "ID",
	ModelType: brandType,
}

func BrandId(expr badorm.Expression[badorm.UIntID]) badorm.WhereCondition[models.Brand] {
	return badorm.FieldCondition[models.Brand, badorm.UIntID]{
		Expression:      expr,
		FieldIdentifier: BrandIdField,
	}
}

var BrandCreatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "CreatedAt",
	ModelType: brandType,
}

func BrandCreatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.Brand] {
	return badorm.FieldCondition[models.Brand, time.Time]{
		Expression:      expr,
		FieldIdentifier: BrandCreatedAtField,
	}
}

var BrandUpdatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "UpdatedAt",
	ModelType: brandType,
}

func BrandUpdatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.Brand] {
	return badorm.FieldCondition[models.Brand, time.Time]{
		Expression:      expr,
		FieldIdentifier: BrandUpdatedAtField,
	}
}

var BrandDeletedAtField = badorm.FieldIdentifier[gorm.DeletedAt]{
	Field:     "DeletedAt",
	ModelType: brandType,
}

func BrandDeletedAt(expr badorm.Expression[gorm.DeletedAt]) badorm.WhereCondition[models.Brand] {
	return badorm.FieldCondition[models.Brand, gorm.DeletedAt]{
		Expression:      expr,
		FieldIdentifier: BrandDeletedAtField,
	}
}

var BrandNameField = badorm.FieldIdentifier[string]{
	Field:     "Name",
	ModelType: brandType,
}

func BrandName(expr badorm.Expression[string]) badorm.WhereCondition[models.Brand] {
	return badorm.FieldCondition[models.Brand, string]{
		Expression:      expr,
		FieldIdentifier: BrandNameField,
	}
}

var BrandPreloadAttributes = badorm.NewPreloadCondition[models.Brand](BrandIdField, BrandCreatedAtField, BrandUpdatedAtField, BrandDeletedAtField, BrandNameField)
