// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"reflect"
	"time"
)

var childType = reflect.TypeOf(*new(models.Child))
var ChildIdField = badorm.FieldIdentifier[badorm.UUID]{
	Field:     "ID",
	ModelType: childType,
}

func ChildId(expr badorm.Expression[badorm.UUID]) badorm.WhereCondition[models.Child] {
	return badorm.FieldCondition[models.Child, badorm.UUID]{
		Expression:      expr,
		FieldIdentifier: ChildIdField,
	}
}

var ChildCreatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "CreatedAt",
	ModelType: childType,
}

func ChildCreatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.Child] {
	return badorm.FieldCondition[models.Child, time.Time]{
		Expression:      expr,
		FieldIdentifier: ChildCreatedAtField,
	}
}

var ChildUpdatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "UpdatedAt",
	ModelType: childType,
}

func ChildUpdatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.Child] {
	return badorm.FieldCondition[models.Child, time.Time]{
		Expression:      expr,
		FieldIdentifier: ChildUpdatedAtField,
	}
}

var ChildDeletedAtField = badorm.FieldIdentifier[gorm.DeletedAt]{
	Field:     "DeletedAt",
	ModelType: childType,
}

func ChildDeletedAt(expr badorm.Expression[gorm.DeletedAt]) badorm.WhereCondition[models.Child] {
	return badorm.FieldCondition[models.Child, gorm.DeletedAt]{
		Expression:      expr,
		FieldIdentifier: ChildDeletedAtField,
	}
}

var ChildNameField = badorm.FieldIdentifier[string]{
	Field:     "Name",
	ModelType: childType,
}

func ChildName(expr badorm.Expression[string]) badorm.WhereCondition[models.Child] {
	return badorm.FieldCondition[models.Child, string]{
		Expression:      expr,
		FieldIdentifier: ChildNameField,
	}
}
func ChildParent1(conditions ...badorm.Condition[models.Parent1]) badorm.IJoinCondition[models.Child] {
	return badorm.JoinCondition[models.Child, models.Parent1]{
		Conditions:         conditions,
		RelationField:      "Parent1",
		T1Field:            "Parent1ID",
		T1PreloadCondition: ChildPreloadAttributes,
		T2Field:            "ID",
	}
}

var ChildPreloadParent1 = ChildParent1(Parent1PreloadAttributes)
var ChildParent1IdField = badorm.FieldIdentifier[badorm.UUID]{
	Field:     "Parent1ID",
	ModelType: childType,
}

func ChildParent1Id(expr badorm.Expression[badorm.UUID]) badorm.WhereCondition[models.Child] {
	return badorm.FieldCondition[models.Child, badorm.UUID]{
		Expression:      expr,
		FieldIdentifier: ChildParent1IdField,
	}
}
func ChildParent2(conditions ...badorm.Condition[models.Parent2]) badorm.IJoinCondition[models.Child] {
	return badorm.JoinCondition[models.Child, models.Parent2]{
		Conditions:         conditions,
		RelationField:      "Parent2",
		T1Field:            "Parent2ID",
		T1PreloadCondition: ChildPreloadAttributes,
		T2Field:            "ID",
	}
}

var ChildPreloadParent2 = ChildParent2(Parent2PreloadAttributes)
var ChildParent2IdField = badorm.FieldIdentifier[badorm.UUID]{
	Field:     "Parent2ID",
	ModelType: childType,
}

func ChildParent2Id(expr badorm.Expression[badorm.UUID]) badorm.WhereCondition[models.Child] {
	return badorm.FieldCondition[models.Child, badorm.UUID]{
		Expression:      expr,
		FieldIdentifier: ChildParent2IdField,
	}
}

var ChildPreloadAttributes = badorm.NewPreloadCondition[models.Child](ChildIdField, ChildCreatedAtField, ChildUpdatedAtField, ChildDeletedAtField, ChildNameField, ChildParent1IdField, ChildParent2IdField)
var ChildPreloadRelations = []badorm.Condition[models.Child]{ChildPreloadParent1, ChildPreloadParent2}
