// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"reflect"
	"time"
)

var cityType = reflect.TypeOf(*new(models.City))
var CityIdField = badorm.FieldIdentifier[badorm.UUID]{
	Field:     "ID",
	ModelType: cityType,
}

func CityId(operator badorm.Operator[badorm.UUID]) badorm.WhereCondition[models.City] {
	return badorm.FieldCondition[models.City, badorm.UUID]{
		FieldIdentifier: CityIdField,
		Operator:        operator,
	}
}

var CityCreatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "CreatedAt",
	ModelType: cityType,
}

func CityCreatedAt(operator badorm.Operator[time.Time]) badorm.WhereCondition[models.City] {
	return badorm.FieldCondition[models.City, time.Time]{
		FieldIdentifier: CityCreatedAtField,
		Operator:        operator,
	}
}

var CityUpdatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "UpdatedAt",
	ModelType: cityType,
}

func CityUpdatedAt(operator badorm.Operator[time.Time]) badorm.WhereCondition[models.City] {
	return badorm.FieldCondition[models.City, time.Time]{
		FieldIdentifier: CityUpdatedAtField,
		Operator:        operator,
	}
}

var CityDeletedAtField = badorm.FieldIdentifier[gorm.DeletedAt]{
	Field:     "DeletedAt",
	ModelType: cityType,
}

func CityDeletedAt(operator badorm.Operator[gorm.DeletedAt]) badorm.WhereCondition[models.City] {
	return badorm.FieldCondition[models.City, gorm.DeletedAt]{
		FieldIdentifier: CityDeletedAtField,
		Operator:        operator,
	}
}

var CityNameField = badorm.FieldIdentifier[string]{
	Field:     "Name",
	ModelType: cityType,
}

func CityName(operator badorm.Operator[string]) badorm.WhereCondition[models.City] {
	return badorm.FieldCondition[models.City, string]{
		FieldIdentifier: CityNameField,
		Operator:        operator,
	}
}
func CityCountry(conditions ...badorm.Condition[models.Country]) badorm.IJoinCondition[models.City] {
	return badorm.JoinCondition[models.City, models.Country]{
		Conditions:         conditions,
		RelationField:      "Country",
		T1Field:            "CountryID",
		T1PreloadCondition: CityPreloadAttributes,
		T2Field:            "ID",
	}
}

var CityPreloadCountry = CityCountry(CountryPreloadAttributes)
var CityCountryIdField = badorm.FieldIdentifier[badorm.UUID]{
	Field:     "CountryID",
	ModelType: cityType,
}

func CityCountryId(operator badorm.Operator[badorm.UUID]) badorm.WhereCondition[models.City] {
	return badorm.FieldCondition[models.City, badorm.UUID]{
		FieldIdentifier: CityCountryIdField,
		Operator:        operator,
	}
}

var CityPreloadAttributes = badorm.NewPreloadCondition[models.City](CityIdField, CityCreatedAtField, CityUpdatedAtField, CityDeletedAtField, CityNameField, CityCountryIdField)
var CityPreloadRelations = []badorm.Condition[models.City]{CityPreloadCountry}
