// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func CompanyId(expr orm.Expression[orm.UUID]) orm.WhereCondition[models.Company] {
	return orm.FieldCondition[models.Company, orm.UUID]{
		Expression: expr,
		Field:      "ID",
	}
}
func CompanyCreatedAt(expr orm.Expression[time.Time]) orm.WhereCondition[models.Company] {
	return orm.FieldCondition[models.Company, time.Time]{
		Expression: expr,
		Field:      "CreatedAt",
	}
}
func CompanyUpdatedAt(expr orm.Expression[time.Time]) orm.WhereCondition[models.Company] {
	return orm.FieldCondition[models.Company, time.Time]{
		Expression: expr,
		Field:      "UpdatedAt",
	}
}
func CompanyDeletedAt(expr orm.Expression[gorm.DeletedAt]) orm.WhereCondition[models.Company] {
	return orm.FieldCondition[models.Company, gorm.DeletedAt]{
		Expression: expr,
		Field:      "DeletedAt",
	}
}
func CompanyName(expr orm.Expression[string]) orm.WhereCondition[models.Company] {
	return orm.FieldCondition[models.Company, string]{
		Expression: expr,
		Field:      "Name",
	}
}
func SellerCompany(conditions ...orm.Condition[models.Company]) orm.Condition[models.Seller] {
	return orm.JoinCondition[models.Seller, models.Company]{
		Conditions: conditions,
		T1Field:    "CompanyID",
		T2Field:    "ID",
	}
}
