// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func CountryId(expr orm.Expression[orm.UUID]) orm.WhereCondition[models.Country] {
	return orm.FieldCondition[models.Country, orm.UUID]{
		Expression: expr,
		Field:      "ID",
	}
}
func CountryCreatedAt(expr orm.Expression[time.Time]) orm.WhereCondition[models.Country] {
	return orm.FieldCondition[models.Country, time.Time]{
		Expression: expr,
		Field:      "CreatedAt",
	}
}
func CountryUpdatedAt(expr orm.Expression[time.Time]) orm.WhereCondition[models.Country] {
	return orm.FieldCondition[models.Country, time.Time]{
		Expression: expr,
		Field:      "UpdatedAt",
	}
}
func CountryDeletedAt(expr orm.Expression[gorm.DeletedAt]) orm.WhereCondition[models.Country] {
	return orm.FieldCondition[models.Country, gorm.DeletedAt]{
		Expression: expr,
		Field:      "DeletedAt",
	}
}
func CountryName(expr orm.Expression[string]) orm.WhereCondition[models.Country] {
	return orm.FieldCondition[models.Country, string]{
		Expression: expr,
		Field:      "Name",
	}
}
func CountryCapital(conditions ...orm.Condition[models.City]) orm.Condition[models.Country] {
	return orm.JoinCondition[models.Country, models.City]{
		Conditions: conditions,
		T1Field:    "ID",
		T2Field:    "CountryID",
	}
}
func CityCountry(conditions ...orm.Condition[models.Country]) orm.Condition[models.City] {
	return orm.JoinCondition[models.City, models.Country]{
		Conditions: conditions,
		T1Field:    "CountryID",
		T2Field:    "ID",
	}
}
