// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func CountryId(v badorm.UUID) badorm.WhereCondition[models.Country] {
	return badorm.WhereCondition[models.Country]{
		Field: "ID",
		Value: v,
	}
}
func CountryCreatedAt(v time.Time) badorm.WhereCondition[models.Country] {
	return badorm.WhereCondition[models.Country]{
		Field: "CreatedAt",
		Value: v,
	}
}
func CountryUpdatedAt(v time.Time) badorm.WhereCondition[models.Country] {
	return badorm.WhereCondition[models.Country]{
		Field: "UpdatedAt",
		Value: v,
	}
}
func CountryDeletedAt(v gorm.DeletedAt) badorm.WhereCondition[models.Country] {
	return badorm.WhereCondition[models.Country]{
		Field: "DeletedAt",
		Value: v,
	}
}
func CountryName(v string) badorm.WhereCondition[models.Country] {
	return badorm.WhereCondition[models.Country]{
		Field: "Name",
		Value: v,
	}
}
func CountryCapital(conditions ...badorm.Condition[models.City]) badorm.Condition[models.Country] {
	return badorm.JoinCondition[models.Country, models.City]{
		Conditions: conditions,
		T1Field:    "ID",
		T2Field:    "CountryID",
	}
}
func CityCountry(conditions ...badorm.Condition[models.Country]) badorm.Condition[models.City] {
	return badorm.JoinCondition[models.City, models.Country]{
		Conditions: conditions,
		T1Field:    "CountryID",
		T2Field:    "ID",
	}
}
