// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func EmployeeId(expr orm.Expression[orm.UUID]) orm.WhereCondition[models.Employee] {
	return orm.FieldCondition[models.Employee, orm.UUID]{
		Expression: expr,
		Field:      "ID",
	}
}
func EmployeeCreatedAt(expr orm.Expression[time.Time]) orm.WhereCondition[models.Employee] {
	return orm.FieldCondition[models.Employee, time.Time]{
		Expression: expr,
		Field:      "CreatedAt",
	}
}
func EmployeeUpdatedAt(expr orm.Expression[time.Time]) orm.WhereCondition[models.Employee] {
	return orm.FieldCondition[models.Employee, time.Time]{
		Expression: expr,
		Field:      "UpdatedAt",
	}
}
func EmployeeDeletedAt(expr orm.Expression[gorm.DeletedAt]) orm.WhereCondition[models.Employee] {
	return orm.FieldCondition[models.Employee, gorm.DeletedAt]{
		Expression: expr,
		Field:      "DeletedAt",
	}
}
func EmployeeName(expr orm.Expression[string]) orm.WhereCondition[models.Employee] {
	return orm.FieldCondition[models.Employee, string]{
		Expression: expr,
		Field:      "Name",
	}
}
func EmployeeBoss(conditions ...orm.Condition[models.Employee]) orm.Condition[models.Employee] {
	return orm.JoinCondition[models.Employee, models.Employee]{
		Conditions: conditions,
		T1Field:    "BossID",
		T2Field:    "ID",
	}
}
func EmployeeBossId(expr orm.Expression[orm.UUID]) orm.WhereCondition[models.Employee] {
	return orm.FieldCondition[models.Employee, orm.UUID]{
		Expression: expr,
		Field:      "BossID",
	}
}
