// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func EmployeeId(v badorm.UUID) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "ID",
		Value: v,
	}
}
func EmployeeCreatedAt(v time.Time) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "CreatedAt",
		Value: v,
	}
}
func EmployeeUpdatedAt(v time.Time) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "UpdatedAt",
		Value: v,
	}
}
func EmployeeDeletedAt(v gorm.DeletedAt) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "DeletedAt",
		Value: v,
	}
}
func EmployeeName(v string) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "Name",
		Value: v,
	}
}
func EmployeeBoss(conditions ...badorm.Condition[models.Employee]) badorm.Condition[models.Employee] {
	return badorm.JoinCondition[models.Employee, models.Employee]{
		Conditions: conditions,
		T1Field:    "BossID",
		T2Field:    "ID",
	}
}
func EmployeeBossId(v *badorm.UUID) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "BossID",
		Value: v,
	}
}
