// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func EmployeeId(v badorm.UUID) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "id",
		Value: v,
	}
}
func EmployeeCreatedAt(v time.Time) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "created_at",
		Value: v,
	}
}
func EmployeeUpdatedAt(v time.Time) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "updated_at",
		Value: v,
	}
}
func EmployeeDeletedAt(v gorm.DeletedAt) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "deleted_at",
		Value: v,
	}
}
func EmployeeName(v string) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "name",
		Value: v,
	}
}
func EmployeeBoss(conditions ...badorm.Condition[models.Employee]) badorm.Condition[models.Employee] {
	return badorm.JoinCondition[models.Employee, models.Employee]{
		Conditions: conditions,
		T1Field:    "boss_id",
		T2Field:    "id",
	}
}
func EmployeeBossId(v *badorm.UUID) badorm.WhereCondition[models.Employee] {
	return badorm.WhereCondition[models.Employee]{
		Field: "boss_id",
		Value: v,
	}
}
