// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func ParentParentId(expr badorm.Expression[badorm.UUID]) badorm.WhereCondition[models.ParentParent] {
	return badorm.FieldCondition[models.ParentParent, badorm.UUID]{
		Expression:      expr,
		FieldIdentifier: badorm.IDFieldID,
	}
}
func ParentParentCreatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.ParentParent] {
	return badorm.FieldCondition[models.ParentParent, time.Time]{
		Expression:      expr,
		FieldIdentifier: badorm.CreatedAtFieldID,
	}
}
func ParentParentUpdatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.ParentParent] {
	return badorm.FieldCondition[models.ParentParent, time.Time]{
		Expression:      expr,
		FieldIdentifier: badorm.UpdatedAtFieldID,
	}
}
func ParentParentDeletedAt(expr badorm.Expression[gorm.DeletedAt]) badorm.WhereCondition[models.ParentParent] {
	return badorm.FieldCondition[models.ParentParent, gorm.DeletedAt]{
		Expression:      expr,
		FieldIdentifier: badorm.DeletedAtFieldID,
	}
}

var parentParentNameFieldID = badorm.FieldIdentifier{Field: "Name"}

func ParentParentName(expr badorm.Expression[string]) badorm.WhereCondition[models.ParentParent] {
	return badorm.FieldCondition[models.ParentParent, string]{
		Expression:      expr,
		FieldIdentifier: parentParentNameFieldID,
	}
}

var ParentParentPreload = badorm.NewPreloadCondition[models.ParentParent](parentParentNameFieldID)
