// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"reflect"
	"time"
)

var personType = reflect.TypeOf(*new(models.Person))
var PersonIdField = badorm.FieldIdentifier[badorm.UUID]{
	Field:     "ID",
	ModelType: personType,
}

func PersonId(expr badorm.Expression[badorm.UUID]) badorm.WhereCondition[models.Person] {
	return badorm.FieldCondition[models.Person, badorm.UUID]{
		Expression:      expr,
		FieldIdentifier: PersonIdField,
	}
}

var PersonCreatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "CreatedAt",
	ModelType: personType,
}

func PersonCreatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.Person] {
	return badorm.FieldCondition[models.Person, time.Time]{
		Expression:      expr,
		FieldIdentifier: PersonCreatedAtField,
	}
}

var PersonUpdatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "UpdatedAt",
	ModelType: personType,
}

func PersonUpdatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.Person] {
	return badorm.FieldCondition[models.Person, time.Time]{
		Expression:      expr,
		FieldIdentifier: PersonUpdatedAtField,
	}
}

var PersonDeletedAtField = badorm.FieldIdentifier[gorm.DeletedAt]{
	Field:     "DeletedAt",
	ModelType: personType,
}

func PersonDeletedAt(expr badorm.Expression[gorm.DeletedAt]) badorm.WhereCondition[models.Person] {
	return badorm.FieldCondition[models.Person, gorm.DeletedAt]{
		Expression:      expr,
		FieldIdentifier: PersonDeletedAtField,
	}
}

var PersonNameField = badorm.FieldIdentifier[string]{
	Field:     "Name",
	ModelType: personType,
}

func PersonName(expr badorm.Expression[string]) badorm.WhereCondition[models.Person] {
	return badorm.FieldCondition[models.Person, string]{
		Expression:      expr,
		FieldIdentifier: PersonNameField,
	}
}

var PersonPreloadAttributes = badorm.NewPreloadCondition[models.Person](PersonIdField, PersonCreatedAtField, PersonUpdatedAtField, PersonDeletedAtField, PersonNameField)
