// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"reflect"
	"time"
)

var phoneType = reflect.TypeOf(*new(models.Phone))
var PhoneIdField = badorm.FieldIdentifier[badorm.UIntID]{
	Field:     "ID",
	ModelType: phoneType,
}

func PhoneId(operator badorm.Operator[badorm.UIntID]) badorm.WhereCondition[models.Phone] {
	return badorm.FieldCondition[models.Phone, badorm.UIntID]{
		FieldIdentifier: PhoneIdField,
		Operator:        operator,
	}
}

var PhoneCreatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "CreatedAt",
	ModelType: phoneType,
}

func PhoneCreatedAt(operator badorm.Operator[time.Time]) badorm.WhereCondition[models.Phone] {
	return badorm.FieldCondition[models.Phone, time.Time]{
		FieldIdentifier: PhoneCreatedAtField,
		Operator:        operator,
	}
}

var PhoneUpdatedAtField = badorm.FieldIdentifier[time.Time]{
	Field:     "UpdatedAt",
	ModelType: phoneType,
}

func PhoneUpdatedAt(operator badorm.Operator[time.Time]) badorm.WhereCondition[models.Phone] {
	return badorm.FieldCondition[models.Phone, time.Time]{
		FieldIdentifier: PhoneUpdatedAtField,
		Operator:        operator,
	}
}

var PhoneDeletedAtField = badorm.FieldIdentifier[gorm.DeletedAt]{
	Field:     "DeletedAt",
	ModelType: phoneType,
}

func PhoneDeletedAt(operator badorm.Operator[gorm.DeletedAt]) badorm.WhereCondition[models.Phone] {
	return badorm.FieldCondition[models.Phone, gorm.DeletedAt]{
		FieldIdentifier: PhoneDeletedAtField,
		Operator:        operator,
	}
}

var PhoneNameField = badorm.FieldIdentifier[string]{
	Field:     "Name",
	ModelType: phoneType,
}

func PhoneName(operator badorm.Operator[string]) badorm.WhereCondition[models.Phone] {
	return badorm.FieldCondition[models.Phone, string]{
		FieldIdentifier: PhoneNameField,
		Operator:        operator,
	}
}
func PhoneBrand(conditions ...badorm.Condition[models.Brand]) badorm.IJoinCondition[models.Phone] {
	return badorm.JoinCondition[models.Phone, models.Brand]{
		Conditions:         conditions,
		RelationField:      "Brand",
		T1Field:            "BrandID",
		T1PreloadCondition: PhonePreloadAttributes,
		T2Field:            "ID",
	}
}

var PhonePreloadBrand = PhoneBrand(BrandPreloadAttributes)
var PhoneBrandIdField = badorm.FieldIdentifier[uint]{
	Field:     "BrandID",
	ModelType: phoneType,
}

func PhoneBrandId(operator badorm.Operator[uint]) badorm.WhereCondition[models.Phone] {
	return badorm.FieldCondition[models.Phone, uint]{
		FieldIdentifier: PhoneBrandIdField,
		Operator:        operator,
	}
}

var PhonePreloadAttributes = badorm.NewPreloadCondition[models.Phone](PhoneIdField, PhoneCreatedAtField, PhoneUpdatedAtField, PhoneDeletedAtField, PhoneNameField, PhoneBrandIdField)
var PhonePreloadRelations = []badorm.Condition[models.Phone]{PhonePreloadBrand}
