// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func PhoneId(operator orm.Operator[orm.UIntID]) orm.WhereCondition[models.Phone] {
	return orm.FieldCondition[models.Phone, orm.UIntID]{
		Operator:      operator,
		FieldIdentifier: orm.IDFieldID,
	}
}
func PhoneCreatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Phone] {
	return orm.FieldCondition[models.Phone, time.Time]{
		Operator:      operator,
		FieldIdentifier: orm.CreatedAtFieldID,
	}
}
func PhoneUpdatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Phone] {
	return orm.FieldCondition[models.Phone, time.Time]{
		Operator:      operator,
		FieldIdentifier: orm.UpdatedAtFieldID,
	}
}
func PhoneDeletedAt(operator orm.Operator[gorm.DeletedAt]) orm.WhereCondition[models.Phone] {
	return orm.FieldCondition[models.Phone, gorm.DeletedAt]{
		Operator:      operator,
		FieldIdentifier: orm.DeletedAtFieldID,
	}
}

var phoneNameFieldID = orm.FieldIdentifier{Field: "Name"}

func PhoneName(operator orm.Operator[string]) orm.WhereCondition[models.Phone] {
	return orm.FieldCondition[models.Phone, string]{
		Operator:      operator,
		FieldIdentifier: phoneNameFieldID,
	}
}
func PhoneBrand(conditions ...orm.Condition[models.Brand]) orm.IJoinCondition[models.Phone] {
	return orm.JoinCondition[models.Phone, models.Brand]{
		Conditions:         conditions,
		RelationField:      "Brand",
		T1Field:            "BrandID",
		T1PreloadCondition: PhonePreloadAttributes,
		T2Field:            "ID",
	}
}

var PhonePreloadBrand = PhoneBrand(BrandPreloadAttributes)
var phoneBrandIdFieldID = orm.FieldIdentifier{Field: "BrandID"}

func PhoneBrandId(operator orm.Operator[uint]) orm.WhereCondition[models.Phone] {
	return orm.FieldCondition[models.Phone, uint]{
		Operator:      operator,
		FieldIdentifier: phoneBrandIdFieldID,
	}
}

var PhonePreloadAttributes = orm.NewPreloadCondition[models.Phone](phoneNameFieldID, phoneBrandIdFieldID)
var PhonePreloadRelations = []orm.Condition[models.Phone]{PhonePreloadBrand}
