// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func ProductId(v badorm.UUID) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "ID",
		Value: v,
	}
}
func ProductCreatedAt(v time.Time) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "CreatedAt",
		Value: v,
	}
}
func ProductUpdatedAt(v time.Time) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "UpdatedAt",
		Value: v,
	}
}
func ProductDeletedAt(v gorm.DeletedAt) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "DeletedAt",
		Value: v,
	}
}
func ProductString(v string) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Column: "string_something_else",
		Value:  v,
	}
}
func ProductInt(v int) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "Int",
		Value: v,
	}
}
func ProductIntPointer(v *int) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "IntPointer",
		Value: v,
	}
}
func ProductFloat(v float64) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "Float",
		Value: v,
	}
}
func ProductBool(v bool) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "Bool",
		Value: v,
	}
}
func ProductByteArray(v []uint8) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "ByteArray",
		Value: v,
	}
}
func ProductMultiString(v models.MultiString) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "MultiString",
		Value: v,
	}
}
func ProductEmbeddedInt(v int) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		Field: "EmbeddedInt",
		Value: v,
	}
}
func ProductGormEmbeddedInt(v int) badorm.WhereCondition[models.Product] {
	return badorm.WhereCondition[models.Product]{
		ColumnPrefix: "gorm_embedded_",
		Field:        "Int",
		Value:        v,
	}
}
