// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func SaleId(exprs ...orm.Expression[orm.UUID]) orm.FieldCondition[models.Sale, orm.UUID] {
	return orm.FieldCondition[models.Sale, orm.UUID]{
		Expressions: exprs,
		Field:       "ID",
	}
}
func SaleCreatedAt(exprs ...orm.Expression[time.Time]) orm.FieldCondition[models.Sale, time.Time] {
	return orm.FieldCondition[models.Sale, time.Time]{
		Expressions: exprs,
		Field:       "CreatedAt",
	}
}
func SaleUpdatedAt(exprs ...orm.Expression[time.Time]) orm.FieldCondition[models.Sale, time.Time] {
	return orm.FieldCondition[models.Sale, time.Time]{
		Expressions: exprs,
		Field:       "UpdatedAt",
	}
}
func SaleDeletedAt(exprs ...orm.Expression[gorm.DeletedAt]) orm.FieldCondition[models.Sale, gorm.DeletedAt] {
	return orm.FieldCondition[models.Sale, gorm.DeletedAt]{
		Expressions: exprs,
		Field:       "DeletedAt",
	}
}
func SaleCode(exprs ...orm.Expression[int]) orm.FieldCondition[models.Sale, int] {
	return orm.FieldCondition[models.Sale, int]{
		Expressions: exprs,
		Field:       "Code",
	}
}
func SaleDescription(exprs ...orm.Expression[string]) orm.FieldCondition[models.Sale, string] {
	return orm.FieldCondition[models.Sale, string]{
		Expressions: exprs,
		Field:       "Description",
	}
}
func SaleProduct(conditions ...orm.Condition[models.Product]) orm.Condition[models.Sale] {
	return orm.JoinCondition[models.Sale, models.Product]{
		Conditions: conditions,
		T1Field:    "ProductID",
		T2Field:    "ID",
	}
}
func SaleProductId(exprs ...orm.Expression[orm.UUID]) orm.FieldCondition[models.Sale, orm.UUID] {
	return orm.FieldCondition[models.Sale, orm.UUID]{
		Expressions: exprs,
		Field:       "ProductID",
	}
}
func SaleSeller(conditions ...orm.Condition[models.Seller]) orm.Condition[models.Sale] {
	return orm.JoinCondition[models.Sale, models.Seller]{
		Conditions: conditions,
		T1Field:    "SellerID",
		T2Field:    "ID",
	}
}
func SaleSellerId(exprs ...orm.Expression[orm.UUID]) orm.FieldCondition[models.Sale, orm.UUID] {
	return orm.FieldCondition[models.Sale, orm.UUID]{
		Expressions: exprs,
		Field:       "SellerID",
	}
}
