// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	badorm "github.com/ditrit/badaas/badorm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"reflect"
	"time"
)

var sellerType = reflect.TypeOf(*new(models.Seller))
var SellerIdField = badorm.FieldIdentifier{
	Field:     "ID",
	ModelType: sellerType,
	Type:      reflect.TypeOf(*new(badorm.UUID)),
}

func SellerId(expr badorm.Expression[badorm.UUID]) badorm.WhereCondition[models.Seller] {
	return badorm.FieldCondition[models.Seller, badorm.UUID]{
		Expression:      expr,
		FieldIdentifier: SellerIdField,
	}
}

var SellerCreatedAtField = badorm.FieldIdentifier{
	Field:     "CreatedAt",
	ModelType: sellerType,
	Type:      reflect.TypeOf(*new(time.Time)),
}

func SellerCreatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.Seller] {
	return badorm.FieldCondition[models.Seller, time.Time]{
		Expression:      expr,
		FieldIdentifier: SellerCreatedAtField,
	}
}

var SellerUpdatedAtField = badorm.FieldIdentifier{
	Field:     "UpdatedAt",
	ModelType: sellerType,
	Type:      reflect.TypeOf(*new(time.Time)),
}

func SellerUpdatedAt(expr badorm.Expression[time.Time]) badorm.WhereCondition[models.Seller] {
	return badorm.FieldCondition[models.Seller, time.Time]{
		Expression:      expr,
		FieldIdentifier: SellerUpdatedAtField,
	}
}

var SellerDeletedAtField = badorm.FieldIdentifier{
	Field:     "DeletedAt",
	ModelType: sellerType,
	Type:      reflect.TypeOf(*new(gorm.DeletedAt)),
}

func SellerDeletedAt(expr badorm.Expression[gorm.DeletedAt]) badorm.WhereCondition[models.Seller] {
	return badorm.FieldCondition[models.Seller, gorm.DeletedAt]{
		Expression:      expr,
		FieldIdentifier: SellerDeletedAtField,
	}
}

var SellerNameField = badorm.FieldIdentifier{
	Field:     "Name",
	ModelType: sellerType,
	Type:      reflect.TypeOf(*new(string)),
}

func SellerName(expr badorm.Expression[string]) badorm.WhereCondition[models.Seller] {
	return badorm.FieldCondition[models.Seller, string]{
		Expression:      expr,
		FieldIdentifier: SellerNameField,
	}
}
func SellerCompany(conditions ...badorm.Condition[models.Company]) badorm.IJoinCondition[models.Seller] {
	return badorm.JoinCondition[models.Seller, models.Company]{
		Conditions:         conditions,
		RelationField:      "Company",
		T1Field:            "CompanyID",
		T1PreloadCondition: SellerPreloadAttributes,
		T2Field:            "ID",
	}
}

var SellerPreloadCompany = SellerCompany(CompanyPreloadAttributes)
var SellerCompanyIdField = badorm.FieldIdentifier{
	Field:     "CompanyID",
	ModelType: sellerType,
	Type:      reflect.TypeOf(*new(badorm.UUID)),
}

func SellerCompanyId(expr badorm.Expression[badorm.UUID]) badorm.WhereCondition[models.Seller] {
	return badorm.FieldCondition[models.Seller, badorm.UUID]{
		Expression:      expr,
		FieldIdentifier: SellerCompanyIdField,
	}
}
func SellerUniversity(conditions ...badorm.Condition[models.University]) badorm.IJoinCondition[models.Seller] {
	return badorm.JoinCondition[models.Seller, models.University]{
		Conditions:         conditions,
		RelationField:      "University",
		T1Field:            "UniversityID",
		T1PreloadCondition: SellerPreloadAttributes,
		T2Field:            "ID",
	}
}

var SellerPreloadUniversity = SellerUniversity(UniversityPreloadAttributes)
var SellerUniversityIdField = badorm.FieldIdentifier{
	Field:     "UniversityID",
	ModelType: sellerType,
	Type:      reflect.TypeOf(*new(badorm.UUID)),
}

func SellerUniversityId(expr badorm.Expression[badorm.UUID]) badorm.WhereCondition[models.Seller] {
	return badorm.FieldCondition[models.Seller, badorm.UUID]{
		Expression:      expr,
		FieldIdentifier: SellerUniversityIdField,
	}
}

var SellerPreloadAttributes = badorm.NewPreloadCondition[models.Seller](SellerIdField, SellerCreatedAtField, SellerUpdatedAtField, SellerDeletedAtField, SellerNameField, SellerCompanyIdField, SellerUniversityIdField)
var SellerPreloadRelations = []badorm.Condition[models.Seller]{SellerPreloadCompany, SellerPreloadUniversity}
