// Code generated by badctl v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func UniversityId(operator orm.Operator[orm.UUID]) orm.WhereCondition[models.University] {
	return orm.FieldCondition[models.University, orm.UUID]{
		Operator:      operator,
		FieldIdentifier: orm.IDFieldID,
	}
}
func UniversityCreatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.University] {
	return orm.FieldCondition[models.University, time.Time]{
		Operator:      operator,
		FieldIdentifier: orm.CreatedAtFieldID,
	}
}
func UniversityUpdatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.University] {
	return orm.FieldCondition[models.University, time.Time]{
		Operator:      operator,
		FieldIdentifier: orm.UpdatedAtFieldID,
	}
}
func UniversityDeletedAt(operator orm.Operator[gorm.DeletedAt]) orm.WhereCondition[models.University] {
	return orm.FieldCondition[models.University, gorm.DeletedAt]{
		Operator:      operator,
		FieldIdentifier: orm.DeletedAtFieldID,
	}
}

var universityNameFieldID = orm.FieldIdentifier{Field: "Name"}

func UniversityName(operator orm.Operator[string]) orm.WhereCondition[models.University] {
	return orm.FieldCondition[models.University, string]{
		Operator:      operator,
		FieldIdentifier: universityNameFieldID,
	}
}

var UniversityPreloadAttributes = orm.NewPreloadCondition[models.University](universityNameFieldID)
