# DEVELOPMENT ONLY, DO NOT USE FOR PRODUCTION
version: '3.5'

services:
  db:
    build: db/.
    ports:
      - "26257:26257"
      - "8080:8080" # Web based dashboard
    environment:
      - COCKROACH_USER=root
      - COCKROACH_DB=badaas_db

  api:
    build:
      context: ./../..
      dockerfile: ./scripts/e2e/api/Dockerfile
    volumes:
      - ../..:/badaas:ro
    entrypoint: go run /badaas/badaas.go --config_path /badaas/scripts/e2e/api/badaas.yml
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
