// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	httperrors "github.com/ditrit/badaas/httperrors"
	mock "github.com/stretchr/testify/mock"
)

// OIDCController is an autogenerated mock type for the OIDCController type
type OIDCController struct {
	mock.Mock
}

// CallBack provides a mock function with given fields: response, request
func (_m *OIDCController) CallBack(response http.ResponseWriter, request *http.Request) (interface{}, httperrors.HTTPError) {
	ret := _m.Called(response, request)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) interface{}); ok {
		r0 = rf(response, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 httperrors.HTTPError
	if rf, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request) httperrors.HTTPError); ok {
		r1 = rf(response, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(httperrors.HTTPError)
		}
	}

	return r0, r1
}

// RedirectURL provides a mock function with given fields: response, request
func (_m *OIDCController) RedirectURL(response http.ResponseWriter, request *http.Request) (interface{}, httperrors.HTTPError) {
	ret := _m.Called(response, request)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) interface{}); ok {
		r0 = rf(response, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 httperrors.HTTPError
	if rf, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request) httperrors.HTTPError); ok {
		r1 = rf(response, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(httperrors.HTTPError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewOIDCController interface {
	mock.TestingT
	Cleanup(func())
}

// NewOIDCController creates a new instance of OIDCController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOIDCController(t mockConstructorTestingTNewOIDCController) *OIDCController {
	mock := &OIDCController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
