@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}

@URI = http://{{hostname}}:{{port}}/v1

@postid = a6515f18-aa94-46d9-8709-29de2a36ea79


# GET all posts
GET {{URI}}/objects/post/ HTTP/1.1
content-type: application/json

###

# GET all post owned by a user
GET {{URI}}/objects/post/?ownerID=23764cb8-80f2-4a03-8060-2f3f4c95b978  HTTP/1.1
content-type: application/json

###

# GET a post
GET {{URI}}/objects/post/{{postid}} HTTP/1.1
content-type: application/json

###

# DELETE all posts
DELETE {{URI}}/objects/post/ HTTP/1.1
content-type: application/json

###

# DELETE a post
DELETE {{URI}}/objects/post/{{postid}} HTTP/1.1
content-type: application/json
