// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import (
	badorm "github.com/ditrit/badaas/badorm"
	uuid "github.com/google/uuid"
	"time"
)

func BicycleIdCondition(v uuid.UUID) badorm.WhereCondition[Bicycle] {
	return badorm.WhereCondition[Bicycle]{
		Field: "id",
		Value: v,
	}
}
func BicycleCreatedAtCondition(v time.Time) badorm.WhereCondition[Bicycle] {
	return badorm.WhereCondition[Bicycle]{
		Field: "created_at",
		Value: v,
	}
}
func BicycleUpdatedAtCondition(v time.Time) badorm.WhereCondition[Bicycle] {
	return badorm.WhereCondition[Bicycle]{
		Field: "updated_at",
		Value: v,
	}
}
func BicycleNameCondition(v string) badorm.WhereCondition[Bicycle] {
	return badorm.WhereCondition[Bicycle]{
		Field: "name",
		Value: v,
	}
}
func BicycleOwnerCondition(conditions ...badorm.Condition[Person]) badorm.Condition[Bicycle] {
	return badorm.JoinCondition[Bicycle, Person]{
		Conditions: conditions,
		Field:      "owner",
	}
}
func BicycleOwnerIdCondition(v uuid.UUID) badorm.WhereCondition[Bicycle] {
	return badorm.WhereCondition[Bicycle]{
		Field: "owner_id",
		Value: v,
	}
}
