// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import (
	badorm "github.com/ditrit/badaas/badorm"
	uuid "github.com/google/uuid"
	"time"
)

func CityIdCondition(v uuid.UUID) badorm.WhereCondition[City] {
	return badorm.WhereCondition[City]{
		Field: "id",
		Value: v,
	}
}
func CityCreatedAtCondition(v time.Time) badorm.WhereCondition[City] {
	return badorm.WhereCondition[City]{
		Field: "created_at",
		Value: v,
	}
}
func CityUpdatedAtCondition(v time.Time) badorm.WhereCondition[City] {
	return badorm.WhereCondition[City]{
		Field: "updated_at",
		Value: v,
	}
}
func CityNameCondition(v string) badorm.WhereCondition[City] {
	return badorm.WhereCondition[City]{
		Field: "name",
		Value: v,
	}
}
func CityCountryIdCondition(v uuid.UUID) badorm.WhereCondition[City] {
	return badorm.WhereCondition[City]{
		Field: "country_id",
		Value: v,
	}
}
