// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import badorm "github.com/ditrit/badaas/badorm"

func BicycleNameCondition(v string) badorm.WhereCondition[Bicycle] {
	return badorm.WhereCondition[Bicycle]{
		Field: "name",
		Value: v,
	}
}
func BicycleOwnerCondition(conditions ...badorm.Condition[Person]) badorm.Condition[Bicycle] {
	return badorm.JoinCondition[Bicycle, Person]{
		Conditions: conditions,
		Field:      "owner",
	}
}
