// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import badorm "github.com/ditrit/badaas/badorm"

func CompanyNameCondition(v string) badorm.WhereCondition[Company] {
	return badorm.WhereCondition[Company]{
		Field: "name",
		Value: v,
	}
}
