// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import badorm "github.com/ditrit/badaas/badorm"

func ProductStringCondition(v string) badorm.WhereCondition[Product] {
	return badorm.WhereCondition[Product]{
		Field: "string",
		Value: v,
	}
}
func ProductIntCondition(v int) badorm.WhereCondition[Product] {
	return badorm.WhereCondition[Product]{
		Field: "int",
		Value: v,
	}
}
func ProductFloatCondition(v float64) badorm.WhereCondition[Product] {
	return badorm.WhereCondition[Product]{
		Field: "float",
		Value: v,
	}
}
func ProductBoolCondition(v bool) badorm.WhereCondition[Product] {
	return badorm.WhereCondition[Product]{
		Field: "bool",
		Value: v,
	}
}
