// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import badorm "github.com/ditrit/badaas/badorm"

func CountryNameCondition(v string) badorm.WhereCondition[Country] {
	return badorm.WhereCondition[Country]{
		Field: "name",
		Value: v,
	}
}
func CountryCapitalCondition(conditions ...badorm.Condition[City]) badorm.Condition[Country] {
	return badorm.JoinCondition[Country, City]{
		Conditions: conditions,
		Field:      "capital",
	}
}
