// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import badorm "github.com/ditrit/badaas/badorm"

func EmployeeNameCondition(v string) badorm.WhereCondition[Employee] {
	return badorm.WhereCondition[Employee]{
		Field: "name",
		Value: v,
	}
}
func EmployeeBossCondition(conditions ...badorm.Condition[Employee]) badorm.Condition[Employee] {
	return badorm.JoinCondition[Employee, Employee]{
		Conditions: conditions,
		Field:      "boss",
	}
}
