// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import (
	badorm "github.com/ditrit/badaas/badorm"
	uuid "github.com/google/uuid"
	"time"
)

func EmployeeIdCondition(v uuid.UUID) badorm.WhereCondition[Employee] {
	return badorm.WhereCondition[Employee]{
		Field: "id",
		Value: v,
	}
}
func EmployeeCreatedAtCondition(v time.Time) badorm.WhereCondition[Employee] {
	return badorm.WhereCondition[Employee]{
		Field: "created_at",
		Value: v,
	}
}
func EmployeeUpdatedAtCondition(v time.Time) badorm.WhereCondition[Employee] {
	return badorm.WhereCondition[Employee]{
		Field: "updated_at",
		Value: v,
	}
}
func EmployeeNameCondition(v string) badorm.WhereCondition[Employee] {
	return badorm.WhereCondition[Employee]{
		Field: "name",
		Value: v,
	}
}
func EmployeeBossCondition(conditions ...badorm.Condition[Employee]) badorm.Condition[Employee] {
	return badorm.JoinCondition[Employee, Employee]{
		Conditions: conditions,
		Field:      "boss",
	}
}
