database:
  host: localhost
  port: 26257 # cockroach
  # port: 5432 # postgree
  sslmode: disable
  username: root # cockroach
  # username: postgres # postgree
  password: postgres
  name: badaas_db
  init:
    retry: 10
    retryTime: 5

logger:
  mode: dev