// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import (
	badorm "github.com/ditrit/badaas/badorm"
	uuid "github.com/google/uuid"
	"time"
)

func PersonIdCondition(v uuid.UUID) badorm.WhereCondition[Person] {
	return badorm.WhereCondition[Person]{
		Field: "id",
		Value: v,
	}
}
func PersonCreatedAtCondition(v time.Time) badorm.WhereCondition[Person] {
	return badorm.WhereCondition[Person]{
		Field: "created_at",
		Value: v,
	}
}
func PersonUpdatedAtCondition(v time.Time) badorm.WhereCondition[Person] {
	return badorm.WhereCondition[Person]{
		Field: "updated_at",
		Value: v,
	}
}
func PersonNameCondition(v string) badorm.WhereCondition[Person] {
	return badorm.WhereCondition[Person]{
		Field: "name",
		Value: v,
	}
}
