// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import badorm "github.com/ditrit/badaas/badorm"

func SaleCodeCondition(v int) badorm.WhereCondition[Sale] {
	return badorm.WhereCondition[Sale]{
		Field: "code",
		Value: v,
	}
}
func SaleDescriptionCondition(v string) badorm.WhereCondition[Sale] {
	return badorm.WhereCondition[Sale]{
		Field: "description",
		Value: v,
	}
}
func SaleProductCondition(conditions ...badorm.Condition[Product]) badorm.Condition[Sale] {
	return badorm.JoinCondition[Sale, Product]{
		Conditions: conditions,
		Field:      "product",
	}
}
func SaleSellerCondition(conditions ...badorm.Condition[Seller]) badorm.Condition[Sale] {
	return badorm.JoinCondition[Sale, Seller]{
		Conditions: conditions,
		Field:      "seller",
	}
}
