// Code generated by badctl v0.0.0, DO NOT EDIT.
package testintegration

import (
	badorm "github.com/ditrit/badaas/badorm"
	uuid "github.com/google/uuid"
	"time"
)

func SellerIdCondition(v uuid.UUID) badorm.WhereCondition[Seller] {
	return badorm.WhereCondition[Seller]{
		Field: "id",
		Value: v,
	}
}
func SellerCreatedAtCondition(v time.Time) badorm.WhereCondition[Seller] {
	return badorm.WhereCondition[Seller]{
		Field: "created_at",
		Value: v,
	}
}
func SellerUpdatedAtCondition(v time.Time) badorm.WhereCondition[Seller] {
	return badorm.WhereCondition[Seller]{
		Field: "updated_at",
		Value: v,
	}
}
func SellerNameCondition(v string) badorm.WhereCondition[Seller] {
	return badorm.WhereCondition[Seller]{
		Field: "name",
		Value: v,
	}
}
func SellerCompanyIdCondition(v *uuid.UUID) badorm.WhereCondition[Seller] {
	return badorm.WhereCondition[Seller]{
		Field: "company_id",
		Value: v,
	}
}
