// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	verdeter "github.com/ditrit/verdeter"
	mock "github.com/stretchr/testify/mock"
)

// CommandsInitializer is an autogenerated mock type for the CommandsInitializer type
type CommandsInitializer struct {
	mock.Mock
}

// Init provides a mock function with given fields: cmd
func (_m *CommandsInitializer) Init(cmd *verdeter.VerdeterCommand) error {
	ret := _m.Called(cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(*verdeter.VerdeterCommand) error); ok {
		r0 = rf(cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCommandsInitializer interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommandsInitializer creates a new instance of CommandsInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommandsInitializer(t mockConstructorTestingTNewCommandsInitializer) *CommandsInitializer {
	mock := &CommandsInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
