name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          skip-cache: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          skip-build-cache: true
      - name: Start containers
        run: docker compose -f "scripts/e2e/docker-compose.yml" up -d --build
      - name: Wait for API server to be up
        uses: mydea/action-wait-for-api@v1
        with:
          url: "http://localhost:8000/info"
          timeout: 20
      - name: Run test
        run:  go test $(go list ./... | grep -v /vendor/) -coverprofile=coverage.out -v
      - name: Get logs 
        if: always()
        run: docker compose -f "scripts/e2e/docker-compose.yml" logs --no-color 2>&1 | tee app.log &
      - name: Stop containers
        if: always()
        run: docker compose -f "scripts/e2e/docker-compose.yml" down
      - uses: actions/upload-artifact@v3
        with:
          name: docker-compose-e2e-logs
          path: app.log
      - name: Check race condition
        run: '! grep -q "WARNING: DATA RACE" app.log'
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
